name: build-image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore: 
      - .github/**
      - .gitignore
      - LICENSE
      - README.md
      - docs/**

jobs:
  build-mistral-image:
    uses: ./.github/workflows/workflow-build-image.yaml
    with:
      registry: quay.io/redhat-ai-services
      image-name: modelcar-catalog
      context: "mistral-7b-instruct-v0.3"
      containerfiles: ./mistral-7b-instruct-v0.3/Containerfile
      tag: "mistral-7b-instruct-v0.3"
    secrets:
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      hf-token: ${{ secrets.HF_TOKEN }}
